### ISSUE TITLE
Change highlighter colour to preserve black text

### ISSUE THREAD

**Issue by ashwinvis** [coderefinery/sphinx-lesson#105]
Currently the highlight colour blends in with the rest of the theme and also inverts the colour of text.

![image](https://github.com/user-attachments/assets/6c19fe4b-328b-458f-b635-0cc2695020a7)

If we add a CSS tweak something like this:

```css
/*** Works on common browsers ***/
::selection {
    background-color: #fce762;
    color: #000;
}

/*** Mozilla based browsers ***/
::-moz-selection {
    background-color: #fce762;
    color: #000;
}

/***For Other Browsers ***/
::-o-selection {
    background-color: #fce762;
    color: #000;
}

::-ms-selection {
    background-color: #fce762;
    color: #000;
}

/*** For Webkit ***/
::-webkit-selection {
    background-color: #fce762;
    color: #000;
}
```

![image](https://github.com/user-attachments/assets/c357e5d3-2dee-4941-a393-92646d1f6316)

**NOTE**: this is inspired from how The Guardian website does this, but I got the CSS from https://stackoverflow.com/questions/2258647/changing-the-highlight-color-when-selecting-text-in-an-html-text-input
